services:
  server:
    build: .
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_POST=6379
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
